# 下载 opencv 4.x
mkdir -p build_32
cd build_32
# 编译动态库
cmake \
-DBUILD_opencv_ittnotify=OFF \
-DBUILD_ITT=OFF \
-DWITH_CUDA=OFF \
-DWITH_OPENCL=OFF \
-DWITH_OPENCLAMDFFT=OFF \
-DWITH_OPENCLAMDBLAS=OFF \
-DWITH_VA_INTEL=OFF \
-DCPU_BASELINE_DISABLE=ON \
-DENABLE_SSE=OFF \
-DENABLE_SSE2=OFF \
-DBUILD_TESTING=OFF \
-DBUILD_PERF_TESTS=OFF \
-DBUILD_TESTS=OFF \
-DCMAKE_BUILD_TYPE=RELEASE \
-DCMAKE_CXX_FLAGS_RELEASE=-g0 \
-DBUILD_EXAMPLES=OFF \
-DBUILD_DOCS=OFF \
-DBUILD_opencv_apps=OFF \
-DBUILD_SHARED_LIBS=ON \
-DOpenCV_STATIC=OFF \
-DWITH_1394=OFF \
-DWITH_ARITH_DEC=OFF \
-DWITH_ARITH_ENC=OFF \
-DWITH_CUBLAS=OFF \
-DWITH_CUFFT=OFF \
-DWITH_FFMPEG=OFF \
-DWITH_GDAL=OFF \
-DWITH_GSTREAMER=OFF \
-DWITH_GTK=OFF \
-DWITH_HALIDE=OFF \
-DWITH_JASPER=OFF \
-DWITH_NVCUVID=OFF \
-DWITH_OPENEXR=OFF \
-DWITH_PROTOBUF=OFF \
-DWITH_PTHREADS_PF=OFF \
-DWITH_QUIRC=OFF \
-DWITH_V4L=OFF \
-DWITH_WEBP=OFF \
-DBUILD_LIST=core,imgproc,highgui \
-DANDROID_NDK=/home/fluence2crane/environment/NDK/android-ndk-r22b/ \
-DCMAKE_TOOLCHAIN_FILE=/home/fluence2crane/environment/NDK/android-ndk-r22b/build/cmake/android.toolchain.cmake \
-DANDROID_NATIVE_API_LEVEL=android-21 \
-DBUILD_JAVA=OFF \
-DBUILD_ANDROID_EXAMPLES=OFF \
-DBUILD_ANDROID_PROJECTS=OFF \
-DANDROID_ABI=armeabi-v7a \
-DBUILD_FAT_JAVA_LIB=OFF \
-DCMAKE_INSTALL_PREFIX=./install_32 \
..
make -j4
make install











mkdir -p build_64
cd build_64
# 编译动态库
cmake \
-DBUILD_opencv_ittnotify=OFF \
-DBUILD_ITT=OFF \
-DWITH_CUDA=OFF \
-DWITH_OPENCL=OFF \
-DWITH_OPENCLAMDFFT=OFF \
-DWITH_OPENCLAMDBLAS=OFF \
-DWITH_VA_INTEL=OFF \
-DCPU_BASELINE_DISABLE=ON \
-DENABLE_SSE=OFF \
-DENABLE_SSE2=OFF \
-DBUILD_TESTING=OFF \
-DBUILD_PERF_TESTS=OFF \
-DBUILD_TESTS=OFF \
-DCMAKE_BUILD_TYPE=RELEASE \
-DCMAKE_CXX_FLAGS_RELEASE=-g0 \
-DBUILD_EXAMPLES=OFF \
-DBUILD_DOCS=OFF \
-DBUILD_opencv_apps=OFF \
-DBUILD_SHARED_LIBS=ON \
-DOpenCV_STATIC=OFF \
-DWITH_1394=OFF \
-DWITH_ARITH_DEC=OFF \
-DWITH_ARITH_ENC=OFF \
-DWITH_CUBLAS=OFF \
-DWITH_CUFFT=OFF \
-DWITH_FFMPEG=OFF \
-DWITH_GDAL=OFF \
-DWITH_GSTREAMER=OFF \
-DWITH_GTK=OFF \
-DWITH_HALIDE=OFF \
-DWITH_JASPER=OFF \
-DWITH_NVCUVID=OFF \
-DWITH_OPENEXR=OFF \
-DWITH_PROTOBUF=OFF \
-DWITH_PTHREADS_PF=OFF \
-DWITH_QUIRC=OFF \
-DWITH_V4L=OFF \
-DWITH_WEBP=OFF \
-DBUILD_LIST=core,imgproc,highgui \
-DANDROID_NDK=/home/fluence2crane/environment/NDK/android-ndk-r22b/ \
-DCMAKE_TOOLCHAIN_FILE=/home/fluence2crane/environment/NDK/android-ndk-r22b/build/cmake/android.toolchain.cmake \
-DANDROID_NATIVE_API_LEVEL=android-21 \
-DBUILD_JAVA=OFF \
-DBUILD_ANDROID_EXAMPLES=OFF \
-DBUILD_ANDROID_PROJECTS=OFF \
-DANDROID_ABI=arm64-v8a \
-DBUILD_FAT_JAVA_LIB=OFF \
-DCMAKE_INSTALL_PREFIX=./install_64 \
..
make -j4
make install